### ISSUE TITLE
[BUG] API - Additional ststus code and message body

### ISSUE THREAD

**Issue by nesyaraa** [Capstone-campyuk/qe-campyuk-APIAutomation#25]

**Comment by nesyaraa** [comment]
please add 400 bad request at post items.

**Comment by kgriffinh** [comment]
done @nesyaraa 



![Image](https://user-images.githubusercontent.com/119381998/218252625-26796074-33b2-4df2-be91-01c9a7b2e85f.png)

**Comment by nesyaraa** [comment]
done
