### ISSUE TITLE
[BUG] API - Scenario Outline: API GET BOOKING with VALID path, INVALID id and VALID token as GUEST

### ISSUE THREAD

**Issue by nesyaraa** [Capstone-campyuk/qe-campyuk-APIAutomation#38]

**Comment by nesyaraa** [comment]
Scenario Outline: API GET BOOKING with VALID path, INVALID id and VALID token AS USER
    Given Base URL is _ and input json body log in guest
    When Set method to POST, Set path to login, and click send button
    Given Get booking with valid path, invalid "<id>" and valid token
    When Send request Get booking invalid id
    Then Should return status code 404
    And API should return body message "booking order not found"

Expected status code <404> but was <500>.



![Image](https://user-images.githubusercontent.com/43703241/218192021-067b441d-513d-469b-b196-18b396f942dd.png)

**Comment by kgriffinh** [comment]
done @nesyaraa 



![Image](https://user-images.githubusercontent.com/119381998/218262132-cbde21c5-2afc-441b-abf0-bfca481a4bc8.png)

**Comment by nesyaraa** [comment]
done
