### ISSUE TITLE
[BUG] API - Scenario Outline: API GET BOOKING with VALID path, INVALID id and VALID token AS HOST

### ISSUE THREAD

**Issue by nesyaraa** [Capstone-campyuk/qe-campyuk-APIAutomation#39]

**Comment by nesyaraa** [comment]
Scenario Outline: API GET BOOKING with VALID path, INVALID id and VALID token AS HOST
    Given Base URL is _ and input json body log in host
    When Set method to POST, Set path to login, and click send button
    Given Get booking with valid path, invalid "<id>" and valid token
    When Send request Get booking invalid id
    Then Should return status code 404
    And API should return body message "booking order not found"

Expected status code <404> but was <500>.


![Image](https://user-images.githubusercontent.com/43703241/218197416-e05222cd-c3fa-42ea-a8c3-84b1c3e1377c.png)

**Comment by kgriffinh** [comment]
done @nesyaraa 



![Image](https://user-images.githubusercontent.com/119381998/218262142-b0fbdb49-71a4-4a2c-93e5-ba081bc8ba6f.png)
