### ISSUE TITLE
[BUG] API - Scenario: API GET BOOKING with VALID ID AS GUEST

### ISSUE THREAD

**Issue by nesyaraa** [Capstone-campyuk/qe-campyuk-APIAutomation#40]

**Comment by nesyaraa** [comment]
Scenario: API GET BOOKING with VALID path AS USER
    Given Base URL is _ and input json body log in guest
    When Set method to POST, Set path to login, and click send button
    Given Get booking with valid path and valid token
    When Send request Get booking valid path
    Then Should return status code 200
    And API should return the right JSON Schema Booking

expected : only returns according to the requested id
actual results : show all transactions

can show all booking, not just 1 id 
![Image](https://user-images.githubusercontent.com/43703241/218198651-a6c5b571-a0d2-43ad-8b16-b7ff0d1b4a18.png)

**Comment by kgriffinh** [comment]
![Image](https://user-images.githubusercontent.com/119381998/218262332-0d03a790-f758-4941-bdf1-b4481bf8d7ed.png)

**Comment by nesyaraa** [comment]
done
