### ISSUE TITLE
[BUG] API - Scenario : API GET BOOKING with VALID ID as HOST

### ISSUE THREAD

**Issue by nesyaraa** [Capstone-campyuk/qe-campyuk-APIAutomation#41]

**Comment by nesyaraa** [comment]
Scenario: API GET BOOKING with VALID ID path as HOST
    Given Base URL is _ and input json body log in host

![Image](https://user-images.githubusercontent.com/43703241/218199616-39a887fb-200b-40ee-9fde-539d5c4f63eb.png)


    When Set method to POST, Set path to login, and click send button
    Given Get booking with valid ID and valid token
    When Send request Get booking valid path
    Then Should return status code 200
    And API should return the right JSON Schema Booking

expected : only returns according to the requested id
actual results : show all transactions

can show all booking, not just 1 id 
![Image](https://user-images.githubusercontent.com/43703241/218198651-a6c5b571-a0d2-43ad-8b16-b7ff0d1b4a18.png)

**Comment by kgriffinh** [comment]
![Image](https://user-images.githubusercontent.com/119381998/218262273-9bf25b02-5373-4725-b26b-79a9b45f6c2f.png)
