### ISSUE TITLE
[BUG] API - Scenario Outline: API POST ACCEPT BOOKING with INVALID id AS HOST

### ISSUE THREAD

**Issue by nesyaraa** [Capstone-campyuk/qe-campyuk-APIAutomation#42]

**Comment by nesyaraa** [comment]
Scenario Outline: API POST ACCEPT BOOKING with INVALID id AS HOST
    Given Base URL is _ and input json body log in host
    When Set method to POST, Set path to login, and click send button
    Given Put booking with invalid "<id>"
    When Send request Put accept booking invalid id
    Then Should return status code 404
    And API should return body message "success accept booking"
    Examples:
      | id |
      | z  |

Expected status code <404> but was <500>.

![Image](https://user-images.githubusercontent.com/43703241/218248141-a1667bb6-019b-49b1-be11-610ff1c9f88e.png)

**Comment by kgriffinh** [comment]
DONE @nesyaraa 

![Image](https://user-images.githubusercontent.com/119381998/218252111-d2f98aab-18b4-4685-8e83-948d3419927a.png)

**Comment by nesyaraa** [comment]
testing clear 
<img width="1440" alt="Jepretan Layar 2023-02-11 pukul 17 10 20" src="https://user-images.githubusercontent.com/43703241/218252435-acb2aa59-5af2-4042-83a3-ef3aec945e4c.png">
