### ISSUE TITLE
[BUG] API - Scenario Outline: API POST CENCELED BOOKING with INVALID id AS HOST

### ISSUE THREAD

**Issue by nesyaraa** [Capstone-campyuk/qe-campyuk-APIAutomation#43]

**Comment by nesyaraa** [comment]
Scenario Outline: API POST CANCELED BOOKING with INVALID id AS HOST
    Given Base URL is _ and input json body log in host
    When Set method to POST, Set path to login, and click send button
    Given Put booking with invalid "<id>"
    When Send request Put cancel booking invalid id
    Then Should return status code 404
    #And API should return body message "Not Found"
    Examples:
      | id |
      | z  |

Expected status code <404> but was <500>.

![Image](https://user-images.githubusercontent.com/43703241/218248208-ca98b73f-6102-4d6b-adfc-c29ddd399a15.png)

**Comment by kgriffinh** [comment]
done @nesyaraa 



![Image](https://user-images.githubusercontent.com/119381998/218252449-ddb82c27-59dc-4561-b6e8-fa8b2907127a.png)

**Comment by nesyaraa** [comment]
testing clear @kgriffinh 
<img width="1440" alt="Jepretan Layar 2023-02-11 pukul 17 13 38" src="https://user-images.githubusercontent.com/43703241/218252568-64d67515-7c6a-41de-a592-e7a59b3aaeb5.png">
