### ISSUE TITLE
[BUG] API - Scenario Outline - API POST CENCELED BOOKING with INVALID id as GUEST

### ISSUE THREAD

**Issue by nesyaraa** [Capstone-campyuk/qe-campyuk-APIAutomation#44]

**Comment by nesyaraa** [comment]
Scenario Outline: API POST CANCELED BOOKING with INVALID id AS USER
    Given Base URL is _ and input json body log in guest
    When Set method to POST, Set path to login, and click send button
    Given Put booking with invalid "<id>"
    When Send request Put cancel booking invalid id
    Then Should return status code 404
    And API should return body message "Not Found"
    Examples:
      | id |
      | z  |

Expected status code <404> but was <500>.

![Image](https://user-images.githubusercontent.com/43703241/218248346-5d6374a3-3779-4081-a3f0-8e278fd54720.png)

**Comment by kgriffinh** [comment]
done @nesyaraa 



![Image](https://user-images.githubusercontent.com/119381998/218252461-ad68e583-053a-42f4-8a7c-34170958ed58.png)

**Comment by nesyaraa** [comment]
testing pass
<img width="1440" alt="Jepretan Layar 2023-02-11 pukul 17 16 42" src="https://user-images.githubusercontent.com/43703241/218252674-e9278189-ead9-43c3-aca1-f48175f6d252.png">
