### ISSUE TITLE
[BUG] API - Scenario -API POST BOOKING CALLBACK BY MIDTRANS with blank transcantion_status

### ISSUE THREAD

**Issue by nesyaraa** [Capstone-campyuk/qe-campyuk-APIAutomation#53]

**Comment by nesyaraa** [comment]
Scenario: API POST BOOKING CALLBACK as with blank status guest
    Given Base URL is _ and input json body log in "nesyaraaUSER" as username and "PUTUSER123" as password
    When Set method to POST, Set path to login, and click send button
    Given Post booking callback with blank status
    When Send request Post booking callback
    Then Should return status code 404
    And API should return body message "booking not found"


expected result : 400 Bad Request
actual result : 200 OK
![Image](https://user-images.githubusercontent.com/43703241/218869066-a9f7931f-8165-424a-adbc-31bf2028e29f.png)

**Comment by helmimuzkr** [comment]
FIXED - given an empty string in the status field, error code 400 bad request will be returned



![Image](https://user-images.githubusercontent.com/84892873/219138991-b3c154df-f4d9-41c3-9914-eccf8d6d0d15.png)
